# Generated by Django 4.1.2 on 2022-10-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='fecha_nac',
        ),
        migrations.AddField(
            model_name='familiares',
            name='parentesco',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
